version: '3.8'
networks:
  u20_network:
services:
  u20-1: # 服务名(唯一)
    image: ${IMAGE}
    container_name: u20 # 容器名(唯一)
    ports:
        # 320xx
        # 3200x: 容器1
        # 3202x: 容器2
        # 3204x: 容器3
      - "32000:22"
      - "32001:8090"
      - "32002:9080"
      - "32003:9990"
      - "32004:9991"
      - "32005:9992"
      - "32006:9993"
      - "32007:9994"
    env_file:
      - .env
    volumes:
      - ${VOLUMES1}
    networks:
      - u20_network
    # 后台运行
    command: tail -f /dev/null

  u20-2:
    image: ${IMAGE}
    container_name: u20-2
    env_file:
      - .env
    ports:
      - "32020:22"
      - "32021:8090"
      - "32022:9080"
      - "32023:9990"
      - "32024:9991"
      - "32025:9992"
      - "32026:9993"
      - "32027:9994"
    volumes:
      - ${VOLUMES1}
    networks:
      - u20_network
    command: tail -f /dev/null
