version: '3.8'
services:
  u18:
    image: hmh:ubuntu18.04-release-1.6.0
    container_name: u18
    ports:
        # 318xx
        # 3180x: 容器1
        # 3182x: 容器2
        # 3184x: 容器3
      - "31800:22"
      - "31801:9990"
      - "31802:9991"
      - "31803:9992"
      - "31804:9993"
    command: tail -f /dev/null

